source "http://rubygems.org"
gem "aruba", "~> 0.2.7"
gem "rake"
gem "rails", ">= 3.0.7"
gem "thin"
gem "shoulda"
gem "sqlite3"
gem "factory_girl"
gem "diesel"
gem "cucumber-rails", '0.3.2'
gem "capybara"
gem "factory_girl_rails"
gem "rspec-rails"
gem "launchy"
gem "mocha"
