source 'http://rubygems.org'

gem 'rails', '3.0.0.beta4'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'mocha'

gem 'formtastic', "1.0.0.beta", :git => "git://github.com/justinfrench/formtastic.git", :branch => "rails3"

gem 'shoulda', '>= 2.11', :git => "git://github.com/thoughtbot/shoulda.git"
gem 'factory_girl_rails'
gem 'nokogiri', '1.4.1'

gem 'capybara'
gem 'database_cleaner'
gem 'cucumber-rails', '0.3.2'
gem 'cucumber', '0.8.5'
gem 'launchy'

gem 'clearance', :path => '../..'
