source 'http://rubygems.org'

gem 'rails', '3.0.0'

gem 'sqlite3-ruby', '1.3.1', :require => 'sqlite3'

gem 'capybara',           '0.3.9'
gem 'cucumber',           '0.8.5'
gem 'cucumber-rails',     '0.3.2'
gem 'factory_girl_rails', '1.0'
gem 'formtastic',         '1.1.0.beta'
gem 'launchy',            '0.3.7'
gem 'mocha',              '0.9.8'
gem 'nokogiri',           '1.4.1'
gem 'shoulda',            '2.11.3'
