name: Run Linter

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"

jobs:
  standardrb:
    name: StandardRB
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.3.11
      - run: bundle exec standardrb --format github --parallel
